name: "Deploy Infrastructure"
on:
  workflow_dispatch:
  push:
    branches: 
    - main

permissions:
  id-token: write
  contents: read

jobs:
  Terraform-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@2ec54502e3e7b5d9591613811da6daded35caa19
        with:
          role-session-name: GitHubActionsSession
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::160071257600:role/jijun6-github-actions-role

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        timeout-minutes: 20

      # Add steps to deploy your terraform code her